#pragma once

enum InjectionStatus
{
	SUCCESS = 0,
	FAILED_PROCESSNOTFOUND,
	FAILED_NOKERNEL32,
	FAILED_NOLOADLIBRARY,
	FAILED_OPENPROCESS,
	FAILED_VIRTUALALLOCEX,	
	FAILED_WRITEPROCESSMEMORY,
	FAILED_CREATEREMOTETHREAD
};